name: CI (repo level)

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"
  workflow_dispatch:
  workflow_call:
  merge_group:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Verify package-lock.json
        run: ./scripts/verify_lock.mjs
      - name: Install dependencies
        run: npm clean-install --ignore-scripts
      # - name: Lint sources
      #   run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test -- --coverage --watchAll=false
      - name: Check
        run: npm run check
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: trustification/trustify-ui
      - name: Crate Format
        working-directory: ./crate
        run: cargo fmt --check
      - name: Crate Check
        working-directory: ./crate
        run: cargo check
      - name: Crate Clippy
        working-directory: ./crate
        run: cargo clippy --all-targets --all-features -- -D warnings
